// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQpHtSeypzGAsFWvu7JKwCFv19fiqSX8o',
    appId: '1:980399647437:web:b31b064ac5c131e40b5784',
    messagingSenderId: '980399647437',
    projectId: 'emt69-13bb4',
    authDomain: 'emt69-13bb4.firebaseapp.com',
    databaseURL: 'https://emt69-13bb4-default-rtdb.firebaseio.com',
    storageBucket: 'emt69-13bb4.appspot.com',
    measurementId: 'G-JF64XFL73E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFAhaOuCeQWZoLbpDOWl5TLHnQEhaUN5U',
    appId: '1:980399647437:android:c9cf77d5c2422c710b5784',
    messagingSenderId: '980399647437',
    projectId: 'emt69-13bb4',
    databaseURL: 'https://emt69-13bb4-default-rtdb.firebaseio.com',
    storageBucket: 'emt69-13bb4.appspot.com',
  );
}
